#!/usr/bin/env python3

## Quick script for adjusting keyboard and screen backlight. https://github.com/ionor 

import sys
import os

BACKLIGHTPATH = "/sys/class/backlight/intel_backlight/"
KEYBOARDPATH  = "/sys/class/leds/smc::kbd_backlight/"

def _get_value(the_path,name):
    try:
        with open(os.path.join(the_path, name), "r") as f:
            return f.read()
    except (OSError, IOError) as err:
        if err.errno == 13:
            print("Error: Permission error")
            sys.exit()

def _set_value(the_path, name, value):
    try:
        with open(os.path.join(the_path, name), "w") as f:
            f.write(str(value))
    except (OSError, IOError) as err:
        if err.errno == 13:
            print("Error: Permission error")
            sys.exit()

def disp_get_actual_in_perc():
    actual = int(_get_value(BACKLIGHTPATH,'actual_brightness'))
    maximum = disp_get_max()

    in_perc = round(100 * (actual/maximum))

    return in_perc

def disp_get_actual():
    actual = int(_get_value(BACKLIGHTPATH,'actual_brightness'))
   # maximum = disp_get_max()
    #in_perc = round(100 * (actual/maximum))

    return actual

def disp_get_max():
    return int(_get_value(BACKLIGHTPATH, "max_brightness"))

def disp_set(value):
    max_value = disp_get_max()
    
    new = _calculate(value, disp_get_actual(), disp_get_max())

    _set_value(BACKLIGHTPATH, "brightness", new)
    return round(100*new/max_value)


def kbd_get_actual_in_perc():
    actual = int(_get_value(KEYBOARDPATH,'brightness'))
    maximum = kbd_get_max()

    in_perc = round(100 * (actual/maximum))
    return in_perc


def kbd_get_actual():
    actual = int(_get_value(KEYBOARDPATH,'brightness'))
    return actual


def kbd_get_max():
    return int(_get_value(KEYBOARDPATH, "max_brightness"))

def kbd_set(value):
    max_value = kbd_get_max()
    new = _calculate(value, kbd_get_actual(), kbd_get_max())
    _set_value(KEYBOARDPATH, "brightness", new)

    return round(100*new/max_value)


def _calculate(value, current, maximum):
    nvalue = str(value)
    nvalue = nvalue.replace('%','')

    if nvalue[0] in ['+','-']:
        direction = nvalue[0]
        the_value = nvalue[1:]

    else:
        direction = '/'
        the_value = nvalue
    
    try: 
        the_value = int(the_value)
    except ValueError:
        _show_usage('Did not understand value. Please write in form (+/-)percentage')
        sys.exit() 

    current_in_perc = round(100* current / maximum)

    if direction == '+':
        #the_change = current_in_perc + the_value
        the_change = max(0, min(current_in_perc + the_value, 100))
        new = round((the_change/100) * maximum) 
        
    elif direction == '-':
        #the_change = current_in_perc - the_value
        the_change = max(0, min(current_in_perc - the_value, 100))
        new = round((the_change/100) * maximum) 

    elif direction == '/':
        the_change = 0
        if 0 <= the_value <= 100:
            new = round((the_value/100) * maximum) 
        else:
            _show_usage('Value out of bound. Must be between 0 and 100')
            sys.exit()

    return new


def _show_usage(errormessage=''):

    if errormessage != '':
        print(errormessage)
        print('')

    print('pyblight [device] [action] [value]')
    print('[device]')
    print('display')
    print('keyboard')
    print('')
    print('[actions]')
    print('get           - get current value')
    print('set           - set new value')
    print('')
    print('[value]')
    print('+X            - increase backlightning')
    print('-X            - decrease backlightning')
    print(' X            - set fixed value. 0-100')
    print('')

# MAIN PART
if __name__ ==  '__main__':
    if len(sys.argv) == 1:
            _show_usage()

    elif (len(sys.argv) > 1) & (sys.argv[1] in ['keyboard','display']):

        if (len(sys.argv) == 2) & (sys.argv[1] in ['keyboard','display']):
            _show_usage('No action specified')

        elif (len(sys.argv) >= 3) & (sys.argv[1] == 'keyboard'):
            if sys.argv[2] == 'set':
                if len(sys.argv) > 3:
                    print(kbd_set(str(sys.argv[3])))
                else:
                    _show_usage('No value supplied')

            elif sys.argv[2] == 'get':
                print(kbd_get_actual_in_perc())

            else:
                _show_usage('Wrong action specified')

        elif (len(sys.argv) >= 3) & (sys.argv[1] == 'display'):
            if sys.argv[2] == 'set':
                if len(sys.argv) > 3:
                    print(disp_set(str(sys.argv[3])))
                else:
                    _show_usage('No value supplied')
            elif sys.argv[2] == 'get':
                print(disp_get_actual_in_perc())
            else:
                _show_usage('Wrong action specified')

    else:
        _show_usage('Wrong or no device specified')



